apiVersion: mdcap.robin.io/v1
kind: ROBINCLUSTER
metadata:
  name: sjc
  flavor: default
  version: '1.0'
  description: 3 node Robin CNP Cluster
  labels:
    location: sjc
spec:
  infra:
    sjc001.robin.io:
      apiVersion: mdcap.robin.io/v1
      kind: BM
      metadata:
        name: sjc001.robin.io
        version: '1.0'
        flavor: default
        description: sjc001.robin.io cluster node
        labels:
          location: sjc
      spec:
        os:
          dns: 10.7.10.21
          ntp: 132.163.96.5
          type: centos
          version: mdcap.robin.io/v1
          hostname: qct36
          domainname: robinsystems.com
          nameserver: 10.7.10.21
          root_password: random_password
        network:
          bootinterface:
            ip: 10.7.90.24
            prefix: '16'
            gateway: 10.7.1.1
        connectors:
          ssh:
            sshhost: 10.0.0.1
            username: https://robinvault/bms/sjc001.robin.io/sshuser
            password: https://robinvault/bms/sjc001.robin.io/sshpass
          bmc:
            bmchost: 10.0.0.1
            username: https://robinvault/bms/sjc001.robin.io/bmcuser
            password: https://robinvault/bms/sjc001.robin.io/bmcpass
        artifactory:
          os_repo_url: http://2.2.2.2/v1/os/centos/7/os/x86_64/
          bmaas_artifactory_url: http://2.2.2.2/v1/
          package_repofile_url: http://2.2.2.2/v1/config/staging.repo
          robin_build_url: http://2.2.2.2:8080/job/Robin_5.2.x_Binary/373/artifact/artifacts/
        config_url: http://10.9.70.51/MARINER/config/unattended_config.json
    sjc002.robin.io:
      apiVersion: mdcap.robin.io/v1
      kind: BM
      metadata:
        name: sjc002.robin.io
        version: '1.0'
        flavor: default
        description: sjc002.robin.io cluster node
        labels:
          location: sjc
      spec:
        os:
          dns: 10.7.10.21
          ntp: 132.163.96.5
          type: centos
          version: mdcap.robin.io/v1
          hostname: qct36
          domainname: robinsystems.com
          nameserver: 10.7.10.21
          root_password: random_password
        network:
          bootinterface:
            ip: 10.7.90.24
            prefix: '16'
            gateway: 10.7.1.1
        connectors:
          ssh:
            sshhost: 10.0.0.2
            username: https://robinvault/bms/sjc002.robin.io/sshuser
            password: https://robinvault/bms/sjc002.robin.io/sshpass
          bmc:
            bmchost: 10.0.0.2
            username: https://robinvault/bms/sjc002.robin.io/bmcuser
            password: https://robinvault/bms/sjc002.robin.io/bmcpass
        artifactory:
          os_repo_url: http://2.2.2.2/v1/os/centos/7/os/x86_64/
          bmaas_artifactory_url: http://2.2.2.2/v1/
          package_repofile_url: http://2.2.2.2/v1/config/staging.repo
          robin_build_url: http://2.2.2.2:8080/job/Robin_5.2.x_Binary/373/artifact/artifacts/
        config_url: http://10.9.70.51/MARINER/config/unattended_config.json
    sjc003.robin.io:
      apiVersion: mdcap.robin.io/v1
      kind: BM
      metadata:
        name: sjc003.robin.io
        version: '1.0'
        flavor: default
        description: sjc003.robin.io cluster node
        labels:
          location: sjc
      spec:
        os:
          dns: 10.7.10.21
          ntp: 132.163.96.5
          type: centos
          version: mdcap.robin.io/v1
          hostname: qct36
          domainname: robinsystems.com
          nameserver: 10.7.10.21
          root_password: random_password
        network:
          bootinterface:
            ip: 10.7.90.24
            prefix: '16'
            gateway: 10.7.1.1
        connectors:
          ssh:
            sshhost: 10.0.0.3
            username: https://robinvault/bms/sjc003.robin.io/sshuser
            password: https://robinvault/bms/sjc003.robin.io/sshpass
          bmc:
            bmchost: 10.0.0.3
            username: https://robinvault/bms/sjc003.robin.io/bmcuser
            password: https://robinvault/bms/sjc003.robin.io/bmcpass
        artifactory:
          os_repo_url: http://2.2.2.2/v1/os/centos/7/os/x86_64/
          bmaas_artifactory_url: http://2.2.2.2/v1/
          package_repofile_url: http://2.2.2.2/v1/config/staging.repo
          robin_build_url: http://2.2.2.2:8080/job/Robin_5.2.x_Binary/373/artifact/artifacts/
        config_url: http://10.9.70.51/MARINER/config/unattended_config.json
  robin_config:
    build_url: http://10.9.200.61:8080/job/Robin_5.2.x_Binary/373/artifact/artifacts/
    server_install_args: "--ignore-warnings"
    agent_install_args: "--ignore-warnings"
    install_type: HA
    ip_pools: []
    name: sjc
    primary_master: sjc001.robin.io
    robin_password: Passw0rd
    robin_user: admin
    secondary_masters:
    - sjc002.robin.io
    - sjc003.robin.io
    agents: []
    security: {}
    version: 5.2.4-373
    vip: 10.10.1.45
    vrid: '222'
