apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfohr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  test:
    enable: true
    ignoreFailures: true
  values:
    resources:
      requests:
        cpu: 110m
        memory: 64Mi
