apiVersion: mdcap.robin.io/v1
kind: NETWORK_SERVICE
metadata:
  name: mdcap
  version: 1.7.1
spec:
  nfpRefs:
    - nfp: mdcapds:1.7.1
      clusterRef:
      - name: cscale-82-119
        kind: ROBINCLUSTER
      - name: cscale-82-120
        kind: ROBINCLUSTER
      - name: cscale-82-121
        kind: ROBINCLUSTER
    - nfp: mdcap:1.7.1
      clusterRef:
      - kind: ROBINCLUSTER
        name: cscale-82-121
    - nfp: haproxy:1.7.1
      clusterRef:
      - kind: ROBINCLUSTER
        name: cscale-82-121        
  hierarchy:
  - mdcapds:1.7.1
  - mdcap:1.7.1
  - haproxy:1.7.1
